#!/bin/sh
if [ "$(dirname "$(realpath "${0}")")" != "$(realpath .)" ]; then
  echo 'ERROR: Please run this command from the repository root (directory)'
  exit 1
fi
if [ -z "$(which zprint)" ]; then
  echo 'ERROR: Missing "zprint" binary; please install it from https://github.com/kkinnear/zprint/releases'
  exit 1
fi
exec zprint '{:cwd-zprintrc? true}' "${@}"
